#!/bin/sh
mount -t proc proc /proc
mount -t sysfs sysfs /sys
mount -t devtmpfs devtmpfs /dev
mount -t tmpfs -o size=256m,nosuid,nodev tmpfs /tmp
mkdir -p /tmp/work /sys/fs/cgroup
mount -t cgroup2 none /sys/fs/cgroup
echo '+memory +pids' > /sys/fs/cgroup/cgroup.subtree_control
exec /usr/bin/python3.10 /agent.py
