import { programs, cases, type PracticeSpec } from "./practice-spec.js";
export const corePractice: PracticeSpec[] = [
  {
    topic: "array",
    title: "인덱스로 배열 값 조회",
    statement:
      "정수 배열과 조회할 인덱스들이 주어집니다. 각 인덱스의 값을 입력 순서대로 한 줄씩 출력하세요. 인덱스는 0부터 시작합니다.",
    input: "n q, 다음 n개 정수, 다음 q개 조회 인덱스",
    output: "각 조회 결과를 한 줄씩 출력하고 마지막에도 줄바꿈",
    constraints: "1 ≤ n,q ≤ 500, |값| ≤ 1000000, 0 ≤ 인덱스 < n",
    time: "O(n+q)",
    space: "O(n+q)",
    tests: cases(
      ["4 3\n8 -2 5 9\n0 3 1\n", "8\n9\n-2\n"],
      ["1 2\n7\n0 0\n", "7\n7\n"],
      ["3 3\n0 0 0\n2 1 0\n", "0\n0\n0\n"],
    ),
    refs: programs(
      `n,q=ni(),ni()\na=[ni() for _ in range(n)]\nfor _ in range(q): print(a[ni()])`,
      `int n,q;cin>>n>>q;vector<long long>a(n);for(auto&x:a)cin>>x;while(q--){int i;cin>>i;cout<<a[i]<<'\\n';}`,
      `int n=sc.nextInt(),q=sc.nextInt();long[] a=new long[n];for(int i=0;i<n;i++)a[i]=sc.nextLong();while(q-->0)System.out.println(a[sc.nextInt()]);`,
    ),
  },
  {
    topic: "linked-list",
    title: "연결 리스트의 머리 삽입과 삭제",
    statement:
      "빈 단일 연결 리스트의 머리에 값을 입력 순서대로 삽입합니다. 이어서 머리 노드를 k번 삭제한 뒤 남은 값을 머리부터 출력하세요. 빈 리스트는 EMPTY를 출력합니다.",
    input: "n k, 이어서 삽입할 n개의 정수",
    output: "남은 값을 공백 하나로 구분하거나 EMPTY, 마지막 줄바꿈",
    constraints: "0 ≤ k ≤ n ≤ 500, |값| ≤ 1000000",
    time: "O(n)",
    space: "O(n)",
    tests: cases(
      ["4 2\n1 2 3 4\n", "2 1\n"],
      ["2 2\n8 9\n", "EMPTY\n"],
      ["0 0\n", "EMPTY\n"],
    ),
    refs: programs(
      `class Node:\n    def __init__(self,value,next_node): self.value=value; self.next=next_node\nn,k=ni(),ni()\nhead=None\nfor _ in range(n): head=Node(ni(),head)\nfor _ in range(k): head=head.next\nout=[]\nwhile head is not None: out.append(str(head.value)); head=head.next\nprint(' '.join(out) if out else 'EMPTY')`,
      `int n,k;cin>>n>>k;Node*head=nullptr;while(n--){long long x;cin>>x;head=new Node{x,head};}while(k--){Node*t=head;head=head->next;delete t;}if(!head)cout<<"EMPTY";bool first=true;while(head){if(!first)cout<<' ';first=false;cout<<head->value;Node*t=head;head=head->next;delete t;}cout<<'\\n';`,
      `int n=sc.nextInt(),k=sc.nextInt();Node head=null;for(int i=0;i<n;i++)head=new Node(sc.nextLong(),head);while(k-->0)head=head.next;StringJoiner out=new StringJoiner(" ");while(head!=null){out.add(""+head.value);head=head.next;}System.out.println(out.length()==0?"EMPTY":out);`,
      `struct Node{long long value;Node*next;};`,
      `static class Node{long value;Node next;Node(long v,Node n){value=v;next=n;}}`,
    ),
  },
  {
    topic: "bst",
    title: "이진 탐색 트리 삽입과 중위 순회",
    statement:
      "값들을 차례로 이진 탐색 트리에 삽입하세요. 같은 값은 한 번만 저장합니다. 완성된 트리의 중위 순회 결과를 출력하세요.",
    input: "n, 이어서 n개의 정수",
    output: "서로 다른 값의 중위 순회 결과를 공백 하나로 구분, 마지막 줄바꿈",
    constraints: "1 ≤ n ≤ 200, |값| ≤ 1000000",
    time: "최악 O(n²)",
    space: "O(n)",
    tests: cases(
      ["7\n8 4 12 2 6 10 14\n", "2 4 6 8 10 12 14\n"],
      ["4\n5 5 5 5\n", "5\n"],
      ["3\n-1 -3 2\n", "-3 -1 2\n"],
    ),
    refs: programs(
      `class Node:\n    def __init__(self,v): self.value=v; self.left=None; self.right=None\ndef insert(t,v):\n    if t is None: return Node(v)\n    if v<t.value: t.left=insert(t.left,v)\n    elif v>t.value: t.right=insert(t.right,v)\n    return t\ndef walk(t):\n    if t is not None: walk(t.left); out.append(str(t.value)); walk(t.right)\nn=ni(); root=None\nfor _ in range(n): root=insert(root,ni())\nout=[]; walk(root); print(' '.join(out))`,
      `int n;cin>>n;Node*root=nullptr;while(n--){int v;cin>>v;root=insert(root,v);}vector<int>out;walk(root,out);for(int i=0;i<(int)out.size();i++){if(i)cout<<' ';cout<<out[i];}cout<<'\\n';`,
      `int n=sc.nextInt();Node root=null;while(n-->0)root=insert(root,sc.nextInt());List<Integer> out=new ArrayList<>();walk(root,out);StringJoiner s=new StringJoiner(" ");for(int v:out)s.add(""+v);System.out.println(s);`,
      `struct Node{int v;Node*l=nullptr,*r=nullptr;};Node*insert(Node*t,int v){if(!t)return new Node{v};if(v<t->v)t->l=insert(t->l,v);else if(v>t->v)t->r=insert(t->r,v);return t;}void walk(Node*t,vector<int>&out){if(!t)return;walk(t->l,out);out.push_back(t->v);walk(t->r,out);}`,
      `static class Node{int v;Node l,r;Node(int x){v=x;}}static Node insert(Node t,int v){if(t==null)return new Node(v);if(v<t.v)t.l=insert(t.l,v);else if(v>t.v)t.r=insert(t.r,v);return t;}static void walk(Node t,List<Integer> out){if(t==null)return;walk(t.l,out);out.add(t.v);walk(t.r,out);}`,
    ),
  },
  {
    topic: "linear-search",
    title: "처음 나타나는 값 찾기",
    statement:
      "정렬되지 않은 배열에서 target이 처음 나타나는 0 기반 인덱스를 출력하세요. 없으면 -1을 출력합니다. 권장 코드는 앞에서부터 비교하는 선형 탐색입니다.",
    input: "n, n개의 정수, target",
    output: "인덱스 또는 -1, 마지막 줄바꿈",
    constraints: "1 ≤ n ≤ 1000, |값|, |target| ≤ 1000000",
    time: "O(n)",
    space: "O(n)",
    tests: cases(
      ["5\n4 2 8 2 9\n2\n", "1\n"],
      ["2\n1 3\n7\n", "-1\n"],
      ["1\n-2\n-2\n", "0\n"],
    ),
    refs: programs(
      `n=ni(); a=[ni() for _ in range(n)]; target=ni(); answer=-1\nfor i in range(n):\n    if a[i]==target: answer=i; break\nprint(answer)`,
      `int n;cin>>n;vector<int>a(n);for(int&v:a)cin>>v;int t,ans=-1;cin>>t;for(int i=0;i<n;i++)if(a[i]==t){ans=i;break;}cout<<ans<<'\\n';`,
      `int n=sc.nextInt();int[] a=new int[n];for(int i=0;i<n;i++)a[i]=sc.nextInt();int t=sc.nextInt(),ans=-1;for(int i=0;i<n;i++)if(a[i]==t){ans=i;break;}System.out.println(ans);`,
    ),
  },
  {
    topic: "sorting",
    title: "정수 목록을 오름차순으로",
    statement:
      "주어진 정수를 오름차순으로 출력하세요. 중복 값을 제거하지 않습니다. 표준 라이브러리 정렬 함수를 사용해도 됩니다.",
    input: "n, 이어서 n개의 정수",
    output: "정렬된 값을 공백 하나로 구분, 마지막 줄바꿈",
    constraints: "1 ≤ n ≤ 1000, |값| ≤ 1000000",
    time: "O(n log n)",
    space: "O(n)",
    tests: cases(
      ["5\n3 -1 3 0 2\n", "-1 0 2 3 3\n"],
      ["1\n0\n", "0\n"],
      ["4\n4 3 2 1\n", "1 2 3 4\n"],
    ),
    refs: programs(
      `n=ni(); a=[ni() for _ in range(n)]; a.sort(); print(*a)`,
      `int n;cin>>n;vector<int>a(n);for(auto&v:a)cin>>v;sort(a.begin(),a.end());for(int i=0;i<n;i++){if(i)cout<<' ';cout<<a[i];}cout<<'\\n';`,
      `int n=sc.nextInt();Integer[] a=new Integer[n];for(int i=0;i<n;i++)a[i]=sc.nextInt();Arrays.sort(a);StringJoiner out=new StringJoiner(" ");for(int v:a)out.add(""+v);System.out.println(out);`,
    ),
  },
  {
    topic: "recursion",
    title: "재귀로 팩토리얼 계산",
    statement:
      "0! = 1, n! = n × (n−1)!를 이용해 n의 팩토리얼을 출력하세요. 권장 코드는 종료 조건이 있는 재귀 함수입니다.",
    input: "정수 n 하나",
    output: "n!과 줄바꿈",
    constraints: "0 ≤ n ≤ 15",
    time: "O(n)",
    space: "O(n)",
    tests: cases(["5\n", "120\n"], ["0\n", "1\n"], ["15\n", "1307674368000\n"]),
    refs: programs(
      `def factorial(n):\n    if n==0: return 1\n    return n*factorial(n-1)\nprint(factorial(ni()))`,
      `int n;cin>>n;cout<<fact(n)<<'\\n';`,
      `System.out.println(fact(sc.nextInt()));`,
      `long long fact(int n){return n==0?1:n*fact(n-1);}`,
      `static long fact(int n){return n==0?1:n*fact(n-1);}`,
    ),
  },
  {
    topic: "brute-force",
    title: "목표에 가장 가까운 두 수의 합",
    statement:
      "서로 다른 두 인덱스를 골라 합을 만들 때 target과의 차이 절댓값의 최솟값을 출력하세요. 권장 코드는 모든 두 인덱스 쌍을 검사합니다.",
    input: "n target, 다음 n개의 정수",
    output: "최소 차이와 줄바꿈",
    constraints: "2 ≤ n ≤ 200, |값|, |target| ≤ 1000000",
    time: "O(n²)",
    space: "O(n)",
    tests: cases(
      ["4 10\n1 4 7 12\n", "1\n"],
      ["2 6\n3 3\n", "0\n"],
      ["3 -10\n-8 -3 4\n", "1\n"],
    ),
    refs: programs(
      `n,target=ni(),ni(); a=[ni() for _ in range(n)]; best=10**18\nfor i in range(n):\n    for j in range(i+1,n): best=min(best,abs(a[i]+a[j]-target))\nprint(best)`,
      `int n;long long t;cin>>n>>t;vector<long long>a(n);for(auto&v:a)cin>>v;long long best=1000000000000000000LL;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)best=min(best,abs(a[i]+a[j]-t));cout<<best<<'\\n';`,
      `int n=sc.nextInt();long t=sc.nextLong();long[] a=new long[n];for(int i=0;i<n;i++)a[i]=sc.nextLong();long best=Long.MAX_VALUE;for(int i=0;i<n;i++)for(int j=i+1;j<n;j++)best=Math.min(best,Math.abs(a[i]+a[j]-t));System.out.println(best);`,
    ),
  },
  {
    topic: "backtracking",
    title: "사전순으로 순열 만들기",
    statement:
      "1부터 n까지 각 정수를 한 번씩 사용하는 모든 순열을 사전순으로 출력하세요. 권장 코드는 선택·재귀 호출·선택 취소를 반복하는 백트래킹입니다.",
    input: "정수 n 하나",
    output: "순열 하나를 한 줄에 출력. 숫자는 공백 하나로 구분, 마지막 줄바꿈",
    constraints: "1 ≤ n ≤ 6",
    time: "O(n × n!)",
    space: "O(n)",
    tests: cases(
      ["3\n", "1 2 3\n1 3 2\n2 1 3\n2 3 1\n3 1 2\n3 2 1\n"],
      ["1\n", "1\n"],
      ["2\n", "1 2\n2 1\n"],
    ),
    refs: programs(
      `n=ni(); used=[False]*(n+1); path=[]\ndef search():\n    if len(path)==n: print(*path); return\n    for v in range(1,n+1):\n        if not used[v]:\n            used[v]=True; path.append(v); search(); path.pop(); used[v]=False\nsearch()`,
      `int n;cin>>n;vector<int>path;vector<bool>used(n+1);function<void()> dfs=[&](){if((int)path.size()==n){for(int i=0;i<n;i++){if(i)cout<<' ';cout<<path[i];}cout<<'\\n';return;}for(int v=1;v<=n;v++)if(!used[v]){used[v]=true;path.push_back(v);dfs();path.pop_back();used[v]=false;}};dfs();`,
      `int n=sc.nextInt();search(n,new int[n],new boolean[n+1],0);`,
      ``,
      `static void search(int n,int[] path,boolean[] used,int depth){if(depth==n){StringJoiner out=new StringJoiner(" ");for(int v:path)out.add(""+v);System.out.println(out);return;}for(int v=1;v<=n;v++)if(!used[v]){used[v]=true;path[depth]=v;search(n,path,used,depth+1);used[v]=false;}}`,
    ),
  },
  {
    topic: "sliding-window",
    title: "길이가 K인 구간의 최대 합",
    statement:
      "연속한 k개 원소의 합 중 최댓값을 구하세요. 모든 원소가 음수여도 정확한 값을 출력해야 합니다. 권장 코드는 구간에서 빠지는 값과 들어오는 값으로 합을 갱신합니다.",
    input: "n k, 이어서 n개의 정수",
    output: "최대 합과 줄바꿈",
    constraints: "1 ≤ k ≤ n ≤ 1000, |값| ≤ 1000000",
    time: "O(n)",
    space: "O(n)",
    tests: cases(
      ["5 3\n1 2 -1 4 3\n", "6\n"],
      ["3 2\n-5 -2 -8\n", "-7\n"],
      ["1 1\n9\n", "9\n"],
    ),
    refs: programs(
      `n,k=ni(),ni();a=[ni() for _ in range(n)];cur=sum(a[:k]);best=cur\nfor i in range(k,n): cur+=a[i]-a[i-k];best=max(best,cur)\nprint(best)`,
      `int n,k;cin>>n>>k;vector<long long>a(n);for(auto&v:a)cin>>v;long long cur=accumulate(a.begin(),a.begin()+k,0LL),best=cur;for(int i=k;i<n;i++){cur+=a[i]-a[i-k];best=max(best,cur);}cout<<best<<'\\n';`,
      `int n=sc.nextInt(),k=sc.nextInt();long[] a=new long[n];for(int i=0;i<n;i++)a[i]=sc.nextLong();long cur=0;for(int i=0;i<k;i++)cur+=a[i];long best=cur;for(int i=k;i<n;i++){cur+=a[i]-a[i-k];best=Math.max(best,cur);}System.out.println(best);`,
    ),
  },
  {
    topic: "greedy",
    title: "겹치지 않는 회의 최대 개수",
    statement:
      "회의마다 시작·종료 시각이 주어집니다. 한 회의 종료 시각과 다음 시작 시각이 같으면 함께 선택할 수 있습니다. 겹치지 않게 선택 가능한 최대 회의 개수를 출력하세요.",
    input: "n, 다음 n줄 시작 시각과 종료 시각",
    output: "최대 개수와 줄바꿈",
    constraints: "0 ≤ n ≤ 1000, 0 ≤ 시작 < 종료 ≤ 1000000",
    time: "O(n log n)",
    space: "O(n)",
    tests: cases(
      ["4\n0 3\n1 2\n2 4\n4 5\n", "3\n"],
      ["0\n", "0\n"],
      ["3\n0 10\n1 9\n2 8\n", "1\n"],
    ),
    refs: programs(
      `n=ni(); meetings=[(ni(),ni()) for _ in range(n)];meetings.sort(key=lambda p:(p[1],p[0]));end=-1;count=0\nfor s,e in meetings:\n    if s>=end: count+=1;end=e\nprint(count)`,
      `int n;cin>>n;vector<pair<int,int>>a;while(n--){int s,e;cin>>s>>e;a.push_back({e,s});}sort(a.begin(),a.end());int end=-1,count=0;for(auto[e,s]:a)if(s>=end){count++;end=e;}cout<<count<<'\\n';`,
      `int n=sc.nextInt();int[][] a=new int[n][2];for(int i=0;i<n;i++){a[i][0]=sc.nextInt();a[i][1]=sc.nextInt();}Arrays.sort(a,Comparator.<int[]>comparingInt(v->v[1]).thenComparingInt(v->v[0]));int end=-1,count=0;for(int[] v:a)if(v[0]>=end){count++;end=v[1];}System.out.println(count);`,
    ),
  },
  {
    topic: "dp",
    title: "동전으로 금액을 만드는 경우의 수",
    statement:
      "서로 다른 동전 종류를 무제한 사용해 금액 m을 만드는 조합의 수를 구하세요. 사용 순서가 달라도 동전 개수가 같으면 같은 조합입니다. 답을 1000000007로 나눈 나머지를 출력하세요.",
    input: "n m, 다음 n개의 서로 다른 동전 값",
    output: "조합 수의 나머지와 줄바꿈",
    constraints: "1 ≤ n ≤ 20, 0 ≤ m ≤ 200, 1 ≤ 동전 값 ≤ 100",
    time: "O(nm)",
    space: "O(n+m)",
    tests: cases(
      ["3 5\n1 2 5\n", "4\n"],
      ["1 0\n3\n", "1\n"],
      ["2 3\n2 4\n", "0\n"],
    ),
    refs: programs(
      `n,m=ni(),ni();coins=[ni() for _ in range(n)];dp=[0]*(m+1);dp[0]=1\nfor c in coins:\n    for s in range(c,m+1):dp[s]=(dp[s]+dp[s-c])%1000000007\nprint(dp[m])`,
      `int n,m;cin>>n>>m;vector<int>coins(n);for(auto&c:coins)cin>>c;vector<long long>dp(m+1);dp[0]=1;for(int c:coins)for(int s=c;s<=m;s++)dp[s]=(dp[s]+dp[s-c])%1000000007;cout<<dp[m]<<'\\n';`,
      `int n=sc.nextInt(),m=sc.nextInt();int[] coins=new int[n];for(int i=0;i<n;i++)coins[i]=sc.nextInt();long[] dp=new long[m+1];dp[0]=1;for(int c:coins)for(int s=c;s<=m;s++)dp[s]=(dp[s]+dp[s-c])%1000000007;System.out.println(dp[m]);`,
    ),
  },
  {
    topic: "memoization",
    title: "메모이제이션 피보나치",
    statement:
      "F(0)=0, F(1)=1, F(n)=F(n−1)+F(n−2)일 때 F(n)을 출력하세요. 권장 코드는 재귀 호출의 결과를 저장해 중복 계산을 줄입니다.",
    input: "정수 n 하나",
    output: "F(n)과 줄바꿈",
    constraints: "0 ≤ n ≤ 90, 답은 부호 있는 64비트 정수 범위",
    time: "O(n)",
    space: "O(n)",
    tests: cases(
      ["10\n", "55\n"],
      ["0\n", "0\n"],
      ["90\n", "2880067194370816120\n"],
    ),
    refs: programs(
      `n=ni();memo={0:0,1:1}\ndef fib(k):\n    if k not in memo: memo[k]=fib(k-1)+fib(k-2)\n    return memo[k]\nprint(fib(n))`,
      `int n;cin>>n;vector<long long>memo(n+2,-1);memo[0]=0;memo[1]=1;function<long long(int)>fib=[&](int k)->long long{if(memo[k]<0)memo[k]=fib(k-1)+fib(k-2);return memo[k];};cout<<fib(n)<<'\\n';`,
      `int n=sc.nextInt();long[] memo=new long[n+2];Arrays.fill(memo,-1);memo[0]=0;memo[1]=1;System.out.println(fib(n,memo));`,
      ``,
      `static long fib(int n,long[] memo){if(memo[n]<0)memo[n]=fib(n-1,memo)+fib(n-2,memo);return memo[n];}`,
    ),
  },
];
