import {
  focusedById,
  practiceTopic,
} from "../../server/src/focused-concepts.js";
type Cost = [time: string, space: string, scope: string];
const base: Record<string, Cost> = {
  array: ["O(1)", "O(1)", "인덱스를 아는 칸의 조회·갱신"],
  "linked-list": ["O(1)", "O(1)", "앞 노드 참조를 아는 삽입·삭제"],
  stack: ["O(1)", "O(1)", "연결 구조의 push·pop 한 번"],
  queue: ["O(1)", "O(1)", "양끝 참조가 있는 큐의 삽입·삭제"],
  hash: ["평균 O(1), 최악 O(n)", "O(1)", "해시 테이블 조회 한 번"],
  heap: ["O(log n)", "O(1)", "반복문으로 구현한 힙 삽입·삭제"],
  "union-find": [
    "상각 O(α(n))",
    "O(n)",
    "크기 병합 + 경로 압축, 전체 부모 배열 포함",
  ],
  trie: ["O(L)", "O(L)", "길이 L 문자열 삽입, 새 노드의 최악 추가 공간"],
  "linear-search": ["O(n)", "O(1)", "정렬되지 않은 배열 탐색"],
  "binary-search": ["O(log n)", "O(1)", "이미 정렬된 배열의 반복 이진 탐색"],
  "brute-force": ["O(n²)", "O(1)", "모든 쌍을 검사하고 최선 값만 보관"],
  backtracking: [
    "O(n·2ⁿ)",
    "O(n)",
    "부분집합을 하나씩 생성, 전체 결과 저장 제외",
  ],
  "two-pointer": ["O(n)", "O(1)", "이미 정렬된 배열의 양끝 포인터 탐색"],
  "sliding-window": ["O(n)", "O(1)", "고정 길이 구간 합, 최댓값만 보관"],
  sorting: ["O(n log n)", "O(n)", "배열 병합 정렬을 선택한 경우"],
  "bubble-sort": ["O(n²)", "O(1)", "버블 정렬의 최악 입력"],
  "selection-sort": ["O(n²)", "O(1)", "선택 정렬 전체 과정"],
  "insertion-sort": ["O(n²)", "O(1)", "삽입 정렬의 역순 입력"],
  "merge-sort": ["O(n log n)", "O(n)", "배열 병합 정렬, 보조 배열 포함"],
  "quick-sort": [
    "평균 O(n log n), 최악 O(n²)",
    "평균 O(log n), 최악 O(n)",
    "제자리 분할, 재귀 스택 포함",
  ],
  tree: ["O(n)", "O(h)", "트리 재귀 순회, 결과 저장 제외; h는 높이"],
  bst: ["O(h), 최악 O(n)", "O(1)", "높이 h인 BST의 반복 탐색"],
  "balanced-tree": ["O(log n)", "O(log n)", "AVL 삽입, 재귀 스택 포함"],
  "segment-tree": [
    "O(log n)",
    "O(n)",
    "점 갱신·구간 질의 한 번, 트리 저장 포함",
  ],
  fenwick: ["O(log n)", "O(n)", "점 갱신·누적 합 질의 한 번, 트리 저장 포함"],
  lca: [
    "전처리 O(n log n), 질의 O(log n)",
    "O(n log n)",
    "이진 점프 테이블 포함",
  ],
  "graph-list": ["O(V+E)", "O(V+E)", "인접 리스트 전체 구성, 그래프 저장 포함"],
  "graph-matrix": ["O(V²)", "O(V²)", "인접 행렬 초기화, 행렬 저장 포함"],
  bfs: ["O(V+E)", "O(V)", "인접 리스트 BFS, 그래프 입력 저장 제외"],
  dfs: ["O(V+E)", "O(V)", "인접 리스트 DFS, 방문 배열·스택 포함"],
  dijkstra: [
    "O((V+E) log V)",
    "O(V+E)",
    "단순 그래프·음이 아닌 간선, 이진 힙의 중복 항목 포함",
  ],
  "bellman-ford": ["O(VE)", "O(V)", "간선 입력 저장 제외, 거리 배열 포함"],
  "floyd-warshall": ["O(V³)", "O(V²)", "거리 행렬 포함"],
  mst: ["O(E log E)", "O(V+E)", "Kruskal 정렬·부모 배열 포함"],
  "topological-sort": [
    "O(V+E)",
    "O(V)",
    "Kahn 알고리즘, 그래프 입력 저장 제외",
  ],
  scc: ["O(V+E)", "O(V+E)", "Kosaraju, 역방향 그래프 포함"],
  flow: ["O(VE²)", "O(V+E)", "Edmonds–Karp, 잔여 인접 리스트 포함"],
  recursion: ["O(n)", "O(n)", "팩토리얼 재귀, 정수 연산을 상수 비용으로 가정"],
  "prefix-sum": ["전처리 O(n), 질의 O(1)", "O(n)", "누적 합 배열 포함"],
  greedy: ["O(n log n)", "O(n)", "종료 시각 기준 회의 선택, 정렬 복사 포함"],
  dp: ["O(n)", "O(n)", "표를 사용하는 피보나치 예제"],
  memoization: ["O(n)", "O(n)", "피보나치 캐시·재귀 스택 포함"],
  tabulation: ["O(n)", "O(n)", "피보나치 상향식 전체 표"],
  "advanced-dp": [
    "O(k n log n)",
    "O(k n)",
    "단조 최적점 가정, k구간 분할 DP 전체 표",
  ],
  kmp: ["O(n+m)", "O(m)", "본문 길이 n, 패턴 길이 m; 일치 위치 저장 제외"],
  geometry: ["O(n log n)", "O(n)", "단조 사슬 볼록 껍질, 정렬 포함"],
  fft: ["O(N log N)", "O(N)", "0 패딩 후 변환 길이 N, 복소수 연산 기준"],
};
const special: Record<string, Cost> = {
  "array-insert": ["O(n)", "O(1)", "남는 용량이 있는 배열의 중간 삽입"],
  "array-traverse": ["O(n)", "O(1)", "배열 합 누적"],
  "stack-parentheses": ["O(n)", "O(n)", "문자열 전체 괄호 검사"],
  "stack-monotonic": ["O(n)", "O(n)", "모든 원소의 다음 큰 값 찾기"],
  "queue-zero-one": [
    "O(V+E)",
    "O(V)",
    "0·1 가중치 그래프, 입력 간선 저장 제외",
  ],
  "hash-frequency": ["평균 O(n)", "O(k)", "서로 다른 키 k개의 빈도 집계"],
  "hash-set": ["평균 O(n)", "O(k)", "n개 입력 중 고유한 k개 키 저장"],
  "hash-load-factor": [
    "O(1)",
    "O(1)",
    "항목·버킷 수를 알 때 적재율 계산; 재해싱 제외",
  ],
  "heap-top-k": ["O(n log k)", "O(k)", "n개 입력에서 상위 k개 유지"],
  "trie-lookup": ["O(L)", "O(1)", "길이 L 문자열 반복 검색, 기존 트라이 제외"],
  "trie-terminal": ["O(1)", "O(1)", "도착 노드의 종료 표시 확인"],
  "brute-force-subsets": [
    "O(n·2ⁿ)",
    "O(n)",
    "부분집합 하나씩 생성, 전체 결과 보관 제외",
  ],
  "two-pointer-merge": ["O(n+m)", "O(n+m)", "두 입력을 새 결과 배열로 병합"],
  "sliding-window-counts": [
    "평균 O(n)",
    "O(k)",
    "해시 빈도표, 구간의 서로 다른 문자 k개",
  ],
  "sorting-compression": ["O(n log n)", "O(n)", "정렬과 순위 매핑 포함"],
  "sorting-deduplicate": ["O(n log n)", "O(n)", "정렬 및 고유 결과 배열 생성"],
  "bubble-sort-early-exit": [
    "최선 O(n), 최악 O(n²)",
    "O(1)",
    "교환 없는 순회에서 조기 종료",
  ],
  "bubble-sort-pass": ["O(n)", "O(1)", "한 번의 순회만 계산"],
  "selection-sort-minimum": ["O(n)", "O(1)", "남은 구간 최솟값 찾기 한 번"],
  "insertion-sort-shift": ["O(n)", "O(1)", "한 원소를 앞 구간에 삽입"],
  "insertion-sort-nearly": [
    "최선 O(n), 최악 O(n²)",
    "O(1)",
    "이동 횟수는 역전쌍 수에 비례",
  ],
  "merge-sort-merge-step": ["O(n+m)", "O(n+m)", "두 구간을 보조 배열로 병합"],
  "quick-sort-partition": ["O(n)", "O(1)", "제자리 분할 한 번"],
  "quick-sort-three-way": ["O(n)", "O(1)", "제자리 3방향 분할 한 번"],
  "tree-children": ["O(1)", "O(1)", "자식 인덱스 계산 한 번"],
  "balanced-tree-height": ["O(1)", "O(1)", "저장된 높이에서 균형 인수 계산"],
  "balanced-tree-rotation": ["O(1)", "O(1)", "높이 갱신 포함 단일 회전 한 번"],
  "balanced-tree-double": ["O(1)", "O(1)", "두 번의 단일 회전"],
  "segment-tree-combine": ["O(1)", "O(1)", "두 자식의 합을 결합하는 한 연산"],
  "fenwick-lowbit": ["O(1)", "O(1)", "고정 폭 정수의 비트 연산"],
  "lca-distance": ["O(1)", "O(1)", "깊이와 LCA를 이미 구한 후 거리 계산"],
  "graph-matrix-lookup": ["O(1)", "O(1)", "이미 구성한 행렬의 한 칸 조회"],
  "graph-matrix-symmetry": ["O(1)", "O(1)", "무방향 간선 한 개 등록"],
  "dijkstra-relax": [
    "O(1)",
    "O(1)",
    "거리 후보 비교·배열 갱신만; 힙 삽입 제외",
  ],
  "dijkstra-stale": ["O(1)", "O(1)", "이미 꺼낸 큐 항목의 유효성 비교"],
  "tabulation-rolling": ["O(n)", "O(1)", "피보나치 두 상태만 유지"],
  "tabulation-knapsack-order": ["O(nW)", "O(W)", "물품 n개, 용량 W인 0/1 배낭"],
  "prefix-sum-two-dimensional": [
    "전처리 O(RC), 질의 O(1)",
    "O(RC)",
    "R행 C열 누적 합",
  ],
  "prefix-sum-difference": [
    "구간 갱신 O(1), 복원 O(n)",
    "O(n)",
    "차분 배열 저장 포함",
  ],
  "kmp-prefix-function": ["O(m)", "O(m)", "길이 m 패턴의 접두사 함수 생성"],
  "geometry-cross": ["O(1)", "O(1)", "고정 폭 좌표 세 점의 외적"],
  "geometry-collinear": ["O(1)", "O(1)", "세 점의 일직선 여부 확인"],
  "fft-convolution": [
    "O(nm)",
    "O(n+m)",
    "계수 쌍을 직접 곱하는 정의 그대로의 구현",
  ],
  "fft-padding": ["O(N)", "O(N)", "새 길이 N 배열에 복사하고 0 채우기"],
  "fft-rounding": ["O(N)", "O(1)", "역변환 결과 N개를 제자리 반올림"],
};
export function conceptCost(id: string): Cost {
  const cost = special[id] ??
    base[practiceTopic(id)] ?? [
      "문제 조건 참고",
      "문제 조건 참고",
      "게시된 문제의 분석 기준을 확인하세요",
    ];
  return [
    cost[0],
    cost[1],
    `${focusedById[id] && !special[id] ? "관련 기본 연산: " : ""}${cost[2]}`,
  ];
}
